### ISSUE TITLE
Set permission group when creating user

### ISSUE THREAD

**Issue by e80tom** [pinkynrg/convergence2.0#129]
![image](https://cloud.githubusercontent.com/assets/17487070/15469774/11385dbc-20b2-11e6-8401-bb2ab4112605.png)

**Comment by pinkynrg** [comment]
The permission group is not associated to the user, it is associated to the contact.
If you try to create a contact now, even in there you won't see the permission group selection. The reason is because the permission groups are different if customer or employee, and by selecting who the new contact belongs to you will also define is it is a customer or contact.

Now by editing the contact I'm the only one able to pick the permission for that contact. By default I set them to be host-employee for the employees and host-customer for customers.
