### ISSUE TITLE
Ticket created with wrong date and older ticket number

### ISSUE THREAD

**Issue by e80tom** [pinkynrg/convergence2.0#150]
![2016-06-01 13_00_43](https://cloud.githubusercontent.com/assets/17487070/15720226/0d2e36f8-27f9-11e6-8ded-843eb8762f2d.png)

I created this ticket on June 1st a bit before 1 pm.  It should have been ticket 4595. I don't know if 4591 existed before I created this one, or if it overwrote something.

**Comment by pinkynrg** [comment]
ticket #4591 didn't exist so no big issue. The reason why the date is shown that way is because you started the draft of the ticket the day before. So the creation of the actual ticket is when you start creating the draft. I will change it so creation and the update date will be paired up once the ticket goes from draft to new.

**Comment by EffEss** [comment]
I started a new ticket, duplicated the tab, and after it posted, it had an old ticket number and a 10-day old creation date. Ticket #4604.  I definitely did not start a ticket draft for this issue 10 days ago.

**Comment by pinkynrg** [comment]
I would like to be more clear in what likely happened so if you all agree I will close the ticket once i push the modification:
If you do visited even once [convergence.elettric80inc.com/tickets/create](https://convergence.elettric80inc.com/tickets/create) page, convergence automatically creates a ticket record with status "draft". 
When I'm saying you created the draft, you didn't necessarily started a draft for that ticket intentionally, but you just visited the ticket creation page without really doing anything. 

So what I'm thinking is that 10 days ago you visited for the first time the ticket creation page and since then you haven't submitted new ticket until today. That's why the old date. 

Does that make sense?

I will fix the issue and update the 2 dates on the above tickets.

**Comment by pinkynrg** [comment]
Solved the issue with the following change before saving the ticket record: 

```
if (isset($ticket->updated_at)) $ticket->created_at = $ticket->updated_at;
```
