### ISSUE TITLE
Can't Edit Contact Name

### ISSUE THREAD

**Issue by e80tom** [pinkynrg/convergence2.0#163]
![image](https://cloud.githubusercontent.com/assets/17487070/15843295/ba99fcb0-2c26-11e6-9414-7ac3c2c18b10.png)

**Comment by pinkynrg** [comment]
The name is not something you are supposed to be able to change. He can change it not other people. I can change for you now. Give the name I'll do it.

You will eventually be able to change it but i need to add a little more input check, as soon as I gave the possibility to change name Jimy changed her name all capitalized. Not ideal. That's why for now you don't have it.

**Comment by pinkynrg** [comment]
What is the name you wanted to change it to?

**Comment by pinkynrg** [comment]
Actually I just gave to the manager group the possibility to change names. So now you are able to change people's name but basic users won't be able to. 

Closing
