### ISSUE TITLE
new equipment note requirement

### ISSUE THREAD

**Issue by raulpm8** [pinkynrg/convergence2.0#51]
when adding new equipment the note field is required, I'm not sure if that is something that we will always have to fill in

**Comment by pinkynrg** [comment]
ok will do. yesterday I was thinking, since we cannot send a post without sending an email to the customer contact, we want the field contact (in the creation ticket form) to be a mandatory field, correct?

And also of course, in the contact form, we do want the email to be a mandatory field, ok?

For all contacts that I imported from C1.0, there are some with no emails (23 out of 560). I guess I won't import those. 

Do you agree?

**Comment by raulpm8** [comment]
ok sounds good

**Comment by pinkynrg** [comment]
done.
